swagger: '2.0'
info:
  version: 1.0.0
  title: MARKETING-Code API
  description: 营销插件-优惠码
host: www.ejw.com
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /code-info:
    get:
      summary: 获取优惠码活动列表
      description: 可以根据状态，名称查询列表
      tags:
        - 优惠码
      parameters:
        - name: codeName
          in: query
          description: 活动名称，模糊匹配
          required: false
          type: string
        - name: status
          in: query
          description: 活动伙伴状态（0：未开始、1：进行中、2：已结束）
          required: true
          type: integer
          enum:
            - 0
            - 1
            - 2
        - name: compId
          in: query
          required: true
          type: string
          description: 企业ID
        - $ref: '#/parameters/PageNo'
        - $ref: '#/parameters/PageSize'
      responses:
        '200':
          description: 优惠码活动列表
          schema:
            $ref: '#/definitions/CodeInfos'
        '400':
          $ref: '#/responses/ParametersErr'
        '500':
          $ref: '#/responses/InnerErr'
    post:
      summary: 添加优惠码活动
      description: 添加优惠码活动
      tags:
        - 优惠码
      parameters:
        - name: codeInfo
          in: body
          description: 需要添加的信息
          schema:
            $ref: '#/definitions/CodeInfoReqPost'
          required: true
      responses:
        '200':
          description: 添加成功
          schema:
            $ref: '#/definitions/CodeInfo'
        '400':
          $ref: '#/responses/ParametersErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-info/{codeId}':
    get:
      summary: 获取优惠码活动
      description: 获取优惠码活动
      tags:
        - 优惠码
      parameters:
        - name: codeId
          in: path
          description: 优惠码活动ID
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: 获取成功
          schema:
            $ref: '#/definitions/CodeInfo'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-info/{codeId}/amount':
    put:
      summary: 修改母码总数
      description: 修改母码总数
      tags:
        - 优惠码
      parameters:
        - name: codeId
          in: path
          required: true
          type: string
          description: codeId
        - name: amount
          in: query
          required: true
          type: integer
          description: 优惠码总数
      responses:
        '200':
          $ref: '#/responses/PutResp'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-info/{codeId}/validFlag':
    put:
      summary: 停止活动
      description: 停止活动
      tags:
        - 优惠码
      parameters:
        - name: codeId
          in: path
          required: true
          type: string
          description: codeId
        - name: validFlag
          in: query
          required: true
          type: string
          description: '0:无效，1：有效'
          enum:
            - 0
            - 1
      responses:
        '200':
          $ref: '#/responses/PutResp'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-info/{codeId}/codeSpec':
    get:
      summary: 获取优惠码子码列表
      description: 获取优惠码子码列表
      tags:
        - 优惠码
      parameters:
        - name: codeId
          in: path
          description: 优惠码ID
          required: true
          type: integer
          format: int32
        - name: specNo
          in: query
          description: 子码编号
          required: false
          type: string
        - $ref: '#/parameters/PageNo'
        - $ref: '#/parameters/PageSize'
      responses:
        '200':
          description: 优惠码子码列表
          schema:
            $ref: '#/definitions/CodeSpecs'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-info/{codeId}/{num}/codeSpec':
    post:
      summary: 添加优惠码子码
      description: 添加优惠码子码
      tags:
        - 优惠码
      parameters:
        - name: codeId
          in: path
          description: 优惠码ID
          required: true
          type: integer
          format: int32
        - name: num
          in: path
          description: 领取数量
          required: true
          type: integer
          format: int32
        - name: codeSpec
          in: body
          description: 需要添加的信息
          schema:
            $ref: '#/definitions/CodeSpecReqPost'
          required: true
      responses:
        '200':
          description: 添加成功
          schema:
            $ref: '#/definitions/CodeSpec'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-info/{codeId}/export':
    get:
      summary: 导出子码列表
      description: 导出子码列表
      tags:
        - 优惠码
      parameters:
        - name: codeId
          in: path
          description: 优惠码ID
          required: true
          type: integer
          format: int32
        - name: specNo
          in: query
          description: 子码编号
          required: false
          type: string
      responses:
        '200':
          description: 优惠码子码列表
          schema:
            $ref: '#/definitions/CodeSpecs'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  '/code-spec/{specId}':
    put:
      summary: 修改子码
      description: 修改子码状态
      tags:
        - 优惠码子码
      parameters:
        - name: specId
          in: path
          description: 优惠码ID
          required: true
          type: string
        - name: codeSpec
          in: body
          description: 需要添加的信息
          schema:
            $ref: '#/definitions/CodeSpecReqPut'
      responses:
        '200':
          description: 优惠码子码列表
          schema:
            $ref: '#/definitions/CodeSpecs'
        '400':
          $ref: '#/responses/ParametersErr'
        '404':
          $ref: '#/responses/NotFoundErr'
        '500':
          $ref: '#/responses/InnerErr'
  /code-spec:
    get:
      summary: 获取优惠码子码列表
      description: 可以根据优惠码名称、子码编码查询列表
      tags:
        - 优惠码子码
      parameters:
        - name: codeName
          in: query
          description: 活动名称，模糊匹配
          required: false
          type: string
        - name: specNo
          in: query
          description: 子码编码
          required: false
          type: string
        - $ref: '#/parameters/PageNo'
        - $ref: '#/parameters/PageSize'
      responses:
        '200':
          description: 优惠码子码列表
          schema:
            $ref: '#/definitions/CodeSpecList'
        '400':
          $ref: '#/responses/ParametersErr'
        '500':
          $ref: '#/responses/InnerErr'
parameters:
  PageNo:
    name: pageNo
    in: query
    description: 当前页码，默认第1页
    required: true
    type: integer
    format: int32
    minimum: 1
    default: 1
  PageSize:
    name: pageSize
    in: query
    description: 每页记录数，默认10条
    required: true
    type: integer
    format: int32
    minimum: 1
    maximum: 99999
    default: 10
responses:
  PutResp:
    description: 修改成功
    schema:
      $ref: '#/definitions/RowsResp'
  ParametersErr:
    description: 参数异常
    schema:
      $ref: '#/definitions/Error'
  NotFoundErr:
    description: 资源不存在
    schema:
      $ref: '#/definitions/Error'
  InnerErr:
    description: 内部错误
    schema:
      $ref: '#/definitions/Error'
definitions:
  CodeInfo:
    type: object
    description: 优惠码活动信息
    properties:
      codeId:
        type: integer
        format: int32
        description: 优惠码ID
      codeName:
        type: string
        description: 优惠码名称
      codeAmount:
        type: integer
        format: int32
        description: 发放数量
      codeImage:
        type: string
        description: 码展示图片(url)
      useType:
        type: string
        description: '使用门槛(0:无金额限制， 1:满减）'
        enum:
          - '0'
          - '1'
      fullValue:
        type: number
        format: float
        description: 满减金额
      codeValue:
        type: number
        format: float
        description: 码金额
      linkUrl:
        type: string
        description: 推广链接
      qrCode:
        type: string
        description: 推广二维码图片
      conditionType:
        type: string
        description: '领码限制(0:无数量限制,1:有数量限制)'
        enum:
          - '0'
          - '1'
      conditionCount:
        type: integer
        format: int32
        description: 领取限制：每个号码限领数量
      publishDateStart:
        type: string
        format: date
        description: 发放（开始领码）开始时间
      publishDateEnd:
        type: string
        format: date
        description: 发放（领取）结束时间
      validDateStart:
        type: string
        description: 使用时间（开始）
      validDateEnd:
        type: string
        description: 使用时间（结束）
      validFlag:
        type: string
        description: '有效标志 0:无效 1:有效'
        enum:
          - '0'
          - '1'
      description:
        type: string
        description: 使用说明
      createTime:
        type: string
        format: date
        description: 创建时间
      modifyTime:
        type: string
        format: date
        description: 修改时间
      createUser:
        type: string
        description: 创建人（员工ID）
      modifyUser:
        type: string
        description: 修改人（员工ID）
      compId:
        type: string
        description: 企业ID
      compName:
        type: string
        description: 企业名称
      status:
        type: string
        description: '优惠码状态(1:未开始，2：进行中，3：已结束)'
        enum:
          - '1'
          - '2'
          - '3'
      receiveAmount:
        type: integer
        description: 领取数
      usedAmount:
        type: integer
        description: 已使用数
  CodeInfos:
    type: object
    description: 优惠码活动输出列表
    properties:
      page:
        description: 总记录数
        type: object
        properties:
          total:
            description: 总记录数
            type: integer
      data:
        description: 目录分类list
        type: array
        items:
          $ref: '#/definitions/CodeInfo'
  CodeSpecList:
    type: object
    description: 优惠码子码输出对象
    properties:
      page:
        description: 总记录数
        type: object
        properties:
          total:
            description: 总记录数
            type: integer
      data:
        type: array
        items:
          $ref: '#/definitions/CodeSpecItem'
  CodeSpecItem:
    type: object
    description: 优惠码与子码信息
    properties:
      codeId:
        type: integer
        format: int32
        description: 优惠码ID
      codeName:
        type: string
        description: 优惠码名称
      specId:
        type: integer
        format: int32
        description: 子码ID
      specNo:
        type: string
        description: 编码为全局唯一的9位数字
        maxLength: 9
      useType:
        type: string
        description: '使用门槛(0:无金额限制， 1:满减）'
        enum:
         - '0'
         - '1'
      fullValue:
        type: number
        format: float
        description: 满减金额
      codeValue:
        type: number
        format: float
        description: 码金额
      specPubTime:
        type: string
        format: date
        description: 领取时间
      specUsedTime:
        type: string
        format: date
        description: 核销时间
  CodeSpec:
    type: object
    description: 优惠码子码信息
    properties:
      specId:
        type: integer
        format: int32
        description: 优惠码子码ID
      specNo:
        type: string
        description: 编码为全局唯一的9位数字
        maxLength: 9
      codeId:
        type: integer
        format: int32
        description: 优惠码ID
      ownerMobile:
        type: string
        description: 领券人手机号
        maxLength: 11
      specState:
        type: string
        description: '券状态0:已领取 1:已锁定 2:已核销（已使用）3：已过期'
        enum:
          - '0'
          - '1'
          - '2'
          - '3'
        maxLength: 1
      specPubType:
        type: string
        format: date
        description: '领取方式0:批量领取，1：个人领取'
        enum:
          - '0'
          - '1'
      specPubTime:
        type: string
        format: date
        description: 领取时间
      specUsedTime:
        type: string
        format: date
        description: 券核销时间
      codeAmount:
        type: integer
        format: int32
        description: 总发放数
      receiveAmount:
        type: integer
        format: int32
        description: 已领取数
      usedAmount:
        type: integer
        format: int32
        description: 已使用数
      orderNo:
        type: string
        description: 用券订单号
      description:
        type: string
        description: '备注,用来保存领券人的信息'
        maxLength: 100
      validCode:
        type: string
        description: 短信验证码
        maxLength: 6
  CodeSpecs:
    type: object
    description: 优惠码子码输出列表
    properties:
      page:
        description: 总记录数
        type: object
        properties:
          total:
            description: 总记录数
            type: integer
      data:
        description: 目录分类list
        type: array
        items:
          $ref: '#/definitions/CodeSpec'
  CodeInfoReqPost:
    type: object
    description: 优惠码活动提交信息
    required:
      - codeName
      - codeAmount
      - fullValue
      - codeValue
      - useType
      - conditionType
      - publishDateStart
      - publishDateEnd
      - validDateStart
      - validDateEnd
      - createUser
      - compId
    allOf:
      - $ref: '#/definitions/CodeInfo'
  CodeSpecReqPost:
    type: object
    description: 优惠码子码提交信息
    required:
      - codeId
      - ownerMobile
      - validCode
    allOf:
      - $ref: '#/definitions/CodeSpec'
  CodeSpecReqPut:
    type: object
    description: 修改优惠码子码信息
    required:
      - specState
    properties:
      specState:
        type: string
        description: '码状态0:已领取 1:已锁定 2:已核销（已使用）3：已过期'
        enum:
          - '0'
          - '1'
          - '2'
          - '3'
  RowsResp:
    type: object
    description: 修改/删除成功响应实体
    properties:
      rows:
        type: integer
        description: 影响行数
  Error:
    type: object
    description: 错误Bean
    required:
      - code
      - msg
    properties:
      code:
        type: string
        description: 错误码
      msg:
        type: string
        description: 错误描述
      errors:
        type: array
        description: 具体错误
        items:
          $ref: '#/definitions/ErrorMsg'
  ErrorMsg:
    type: object
    description: 错误消息详细信息
    properties:
      field:
        type: string
        description: 错误字段
      msg:
        type: string
        description: 错误原因
