# Code completion support is available so start typing for available options.
swagger: '2.0'

info:
  version: "1.2.2"
  title: PortalService  API
  description: 业务服务--门户服务接口说明

host: ejw.hnjing.com
#host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

#数据返回的约定
#1.响应码只有200、400、403、404、405、500。
#2.获取列表接口无数据时响应码200，返回空列表和page信息。
#3.获取单个资源接口无数据时响应码404，返回404错误信息。
#4.路径中的参数错误导致资源不存在，响应码404，返回404错误信息。
#5.没有权限读取、修改、删除资源响应码403，返回403错误信息。
#6.输入参数校验失败响应码400，返回400错误信息。
#7.资源没有对应的方法响应码405，返回405错误信息。
#8.删除资源时同时删除其相关关联关系，不要产生500错误。

#必填字段约定
#1.必填是指添加或修改信息时，该字段必须传值。
#2.修改信息时必填字段可以不传，即为不修改。

################################################################################
#                              API Information                                 #
################################################################################ 
paths:

  /partners:
    get:
      summary: 获取合作伙伴列表
      description: 获取合作伙伴列表
      tags: 
        - 合作伙伴信息
      parameters:
        - name: partnerName
          in: query
          description: 合作伙伴名称
          required: false
          type: string
        - $ref: '#/parameters/Status'
        - $ref: '#/parameters/PageNo'
        - $ref: '#/parameters/PageSize'
        - $ref: '#/parameters/Sort'
          
      responses:
        200:
          description: 合作伙伴列表
          schema:
            $ref: '#/definitions/Partners'
        400:
          $ref: '#/responses/ParametersErr'
        500:
          $ref: '#/responses/InnerErr'
  
  /user/partners:
    get:
      summary: 获取用户提交的合作伙伴列表
      description: 获取用户提交的合作伙伴列表
      tags: 
        - 合作伙伴信息
      parameters:
        - $ref: '#/parameters/UserId'
        - $ref: '#/parameters/Status'
        - $ref: '#/parameters/PageNo'
        - $ref: '#/parameters/PageSize'
        - $ref: '#/parameters/Sort'
          
      responses:
        200:
          description: 合作伙伴列表
          schema:
            $ref: '#/definitions/Partners'
        400:
          $ref: '#/responses/ParametersErr'
        500:
          $ref: '#/responses/InnerErr'
          
  /partners/quick:
    get:
      summary: 合作伙伴快速搜索
      description: 合作伙伴快速搜索，合作伙伴名称模糊匹配，合作伙伴状态全匹配。优先显示以输入的合作伙伴名称开头的记录，当记录数不足时，再显示含输入的合作伙伴名称的记录。
      tags: 
        - 合作伙伴信息
      parameters:
        -
          name: partnerName
          in: query
          description: 合作伙伴名称
          required: false
          type: string
        - $ref: '#/parameters/Status'
        -
          name: limit
          in: query
          description: 返回记录数，默认10条
          required: false
          type: integer
          format: int32
          maximum: 20
          default: 10
          
      responses:
        200:
          description: 合作伙伴列表
          schema:
            $ref: '#/definitions/PartnerQuick'
        400:
          $ref: '#/responses/ParametersErr'
        500:
          $ref: '#/responses/InnerErr'
            
  /partner/{partnerId}:
    put:
      summary: 修改合作伙伴基础信息
      description: 修改合作伙伴基础信息
      tags: 
        - 合作伙伴信息
      parameters:
        - $ref: '#/parameters/PartnerId'
        -
          name: partner
          in: body
          description: 需要修改的信息
          schema:
            $ref: '#/definitions/PartnerReqPut'
          required: true

      responses:
        200:
          $ref: '#/responses/PutResp'
        400:
          $ref: '#/responses/ParametersErr'
        404:
          $ref: '#/responses/NotFoundErr'
        500:
          $ref: '#/responses/InnerErr'
            
  /partnerall:
    post:
      summary: 添加合作伙伴信息
      description: 添加合作伙伴信息
      tags: 
        - 合作伙伴信息
      parameters:
        - $ref: '#/parameters/UserId'
        -
          name: partner
          in: body
          description: 需要添加的信息
          schema:
            $ref: '#/definitions/PartnerAllReqPost'
          required: true

      responses:
        200:
          description: 添加成功
          schema:
            $ref: '#/definitions/PartnerAllResp'
        400:
          $ref: '#/responses/ParametersErr'
        500:
          $ref: '#/responses/InnerErr'
                
  /partnerall/{partnerId}:
    get:
      summary: 获取合作伙伴信息
      description: 获取合作伙伴信息
      tags: 
        - 合作伙伴信息
      parameters:
        - $ref: '#/parameters/PartnerId'
          
      responses:
        200:
          description: 合作伙伴信息
          schema:
            $ref: '#/definitions/PartnerAllResp'
        400:
          $ref: '#/responses/ParametersErr'
        404:
          $ref: '#/responses/NotFoundErr'
        500:
          $ref: '#/responses/InnerErr'
      
    put:
      summary: 修改合作伙伴信息
      description: 修改合作伙伴信息
      tags: 
        - 合作伙伴信息
      parameters:
        - $ref: '#/parameters/PartnerId'
        -
          name: partner
          in: body
          description: 需要修改的信息
          schema:
            $ref: '#/definitions/PartnerAllReqPut'
          required: true

      responses:
        200:
          $ref: '#/responses/PutResp'
        400:
          $ref: '#/responses/ParametersErr'
        404:
          $ref: '#/responses/NotFoundErr'
        500:
          $ref: '#/responses/InnerErr'
            
    delete: 
      summary: 删除合作伙伴
      description: 删除合作伙伴需要同时删除其基本、扩展、资质、员工信息
      tags: 
        - 合作伙伴信息
      parameters:
        - $ref: '#/parameters/PartnerId'
      responses:
        200:
          $ref: '#/responses/DeleteResp'
        400:
          $ref: '#/responses/ParametersErr'
        404:
          $ref: '#/responses/NotFoundErr'
        500:
          $ref: '#/responses/InnerErr'
            
################################################################################
#                                 Parameters                                  #
################################################################################
parameters:
  PageNo:
    name: pageNo
    in: query
    description: 当前页码，默认第1页
    required: false
    type: integer
    format: int32
    minimum: 1
    default: 1
    
  PageSize:
    name: pageSize
    in: query
    description: 每页记录数，默认10条
    required: false
    type: integer
    format: int32
    minimum: 1
    maximum: 99999
    default: 10
    
  Sort:  
    name: sort
    in: query
    description: 排序方式，json格式：{"id":"asc","name":"desc"} ，必须Url编码
    required: false
    type: string
    format: json
  
  PartnerId:
    name: partnerId
    in: path
    description: 合作伙伴id
    required: true
    type: integer
  
  UserId:
    name: user-id
    in: header
    description: 当前操作用户id
    required: true
    type: string
          
  Status:
    name: status
    in: query
    enum:
      - 0
      - 1
      - 2
    description: 合作伙伴审核状态，0：未审核；2：审核不通过
    required: false
    type: integer
################################################################################
#                                 Responses                                  #
################################################################################
responses:
  PutResp:
    description: 修改成功
      
  DeleteResp:
    description: 删除成功

  ParametersErr:
    description: 参数异常
    schema:
      $ref: '#/definitions/Error'
  
  NotFoundErr:
    description: 资源不存在
    schema:
      $ref: '#/definitions/Error'
      
  InnerErr:
    description: 内部错误
    schema:
      $ref: '#/definitions/Error'
            
################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  Gmt:
    type: object
    description: 时间信息
    properties:
      gmtCreate:
        type: string
        format: date-time
        description: 创建时间
      gmtModified:
        type: string
        format: date-time
        description: 修改时间
        
  PartnerQuick:
    type: object
    description: 合作伙伴信息
    properties:
      partnerId:
        type: integer
        description: 合作伙伴id
      partnerName:
        type: string
        description: 合作伙伴名称
  
  PartnerReqPost:
    type: object
    description: 合作伙伴添加实体
    required:
    - partnerName
    - area
    - address
    - phone
    - status
    allOf:
    - $ref: '#/definitions/Partner'
    
  PartnerReqPut:
    type: object
    description: 合作伙伴修改实体
    allOf:
    - $ref: '#/definitions/Partner'
  
  PartnerResp:
    type: object
    description: 合作伙伴响应实体
    allOf:
    - $ref: '#/definitions/Partner'
    - $ref: '#/definitions/Gmt'
    properties:
      partnerId:
        type: integer
        description: 合作伙伴id
      userId:
        type: integer
        description: 管理员用户id
  
  Partner:
    type: object
    description: 合作伙伴信息
    properties:
      partnerNo:
        type: string
        description: 合作伙伴代码
        maxLength: 20
      partnerName:
        type: string
        description: 合作伙伴名称
        minLength: 1
        maxLength: 50
      area:
        type: string
        description: 所在地区
        minLength: 1
        maxLength: 50
      address:
        type: string
        description: 详细地址
        minLength: 1
        maxLength: 50
      tradingArea:
        type: string
        description: 所属商圈
        maxLength: 30
      phone:
        type: string
        description: 企业电话，多个号码以英文逗号分隔，最多5个
        minLength: 1
        maxLength: 100
      fax:
        type: string
        description: 企业传真，多个号码以英文逗号分隔，最多5个
        maxLength: 100
      status:
        type: integer
        enum: 
          - 0
          - 1
          - 2
        description: 审核状态，0：未审核；2：审核不通过，默认0
        default: 1
      detail:
        type: string
        description: 详细介绍，0-500字符
        maxLength: 500
      longitude:
        type: number
        format: double
        description: 经度，-180~180，最多8位小数
        maximum: 180
        minimum: -180
      latitude:
        type: number
        format: double
        description: 纬度，-90~90，最多8位小数
        maximum: 90
        minimum: -90
      organizeType:
        type: integer
        enum: 
          - 1
          - 2
          - 3
          - 4
          - 5
        description: 组织类型，必填，1：企业/个体工商户；2：事业法人；3：社团法人；4：基金会；5：民办非企业
      createUser:
        type: integer
        description: 创建人（用户id，对应US），添加修改时无此参数，添加时从header中取
      auditUser:
        type: integer
        description: 审核用户id，添加时无此参数
      auditMsg:
        type: string
        description: 审核意见，0-50字符，添加时无此参数。修改时如果auditMsg不为空则同时修改audit_time为当前时间。
  
  PartnerExtReqPost:
    type: object
    description: 合作伙伴扩展添加实体
    allOf:
    - $ref: '#/definitions/PartnerExt'
    
  PartnerExtReqPut:
    type: object
    description: 合作伙伴扩展修改实体
    allOf:
    - $ref: '#/definitions/PartnerExt'
  
  PartnerExtResp:
    type: object
    description: 合作伙伴扩展响应实体
    allOf:
    - $ref: '#/definitions/PartnerExt'
    - $ref: '#/definitions/Gmt'
    properties:
      partnerId:
        type: integer
        description: 合作伙伴id
        
  PartnerExt:
    type: object
    description: 合作伙伴扩展信息
    properties:
      platformIndustry:
        type: string
        description: 平台业务行业，多个行业id以英文逗号分隔
        maxLength: 50
      standardIndustry:
        type: string
        description: 所属国标行业，多个行业id以英文逗号分隔
        maxLength: 50
      scale:
        type: integer
        enum: 
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
        description: 企业规模，1：1-10人，2：10-50人，3：50-100人，4：100-300人，5：300-500人，6：500人以上
      mainBusiness:
        type: string
        description: 主营业务/产品
        maxLength: 100
      manageType:
        type: integer
        enum: 
          - 1
          - 2
          - 3
          - 4
        description: 经营模式，1：自产自销，2：代理，3：加盟，4：劳务合作
      logo:
        type: string
        description: 品牌
        maxLength: 20
      website:
        type: string
        description: 网址，多个网址以英文逗号分隔，最多5个
        maxLength: 200
  
  PartnerQualifyReqPost:
    type: object
    description: 合作伙伴资质添加实体
    required:
    - qualifyImage
    allOf:
    - $ref: '#/definitions/PartnerQualify'
  
  PartnerQualifyReqPut:
    type: object
    description: 合作伙伴资质修改实体
    allOf:
    - $ref: '#/definitions/PartnerQualify'
  
  PartnerQualifyResp:
    type: object
    description: 合作伙伴资质响应实体
    allOf:
    - $ref: '#/definitions/PartnerQualify'
    - $ref: '#/definitions/Gmt'
    properties:
      partnerId:
        type: integer
        description: 合作伙伴id
      qualifyId:
        type: integer
        description: 资质信息id
        
  PartnerQualify:
    type: object
    description: 合作伙伴资质信息
    properties:
      qualifyType:
        type: integer
        description: 资质类型
      qualifyName:
        type: string
        description: 资质名称
        maxLength: 50
      qualifyValidDate:
        type: string
        format: date-time
        description: 资质有效期
      qualifyImage:
        type: string
        description: 资质图片
        minLength: 1
        maxLength: 1000
      qualifyRemark:
        type: string
        description: 备注
        maxLength: 500
  
  PartnerAllReqPost:
    type: object
    description: 合作伙伴全量信息添加实体
    required:
    - partner
    properties:
      partner:
        $ref: '#/definitions/PartnerReqPost'
      partnerExt:
        $ref: '#/definitions/PartnerExtReqPost'
      partnerQualify:
        $ref: '#/definitions/PartnerQualifyReqPost'
      employee:
        $ref: '#/definitions/EmployeeReqPost'
  
  PartnerAllReqPut:
    type: object
    description: 合作伙伴全量信息修改实体
    properties:
      partner:
        $ref: '#/definitions/PartnerReqPut'
      partnerExt:
        $ref: '#/definitions/PartnerExtReqPut'
      partnerQualify:
        $ref: '#/definitions/PartnerQualifyReqPut'
      employee:
        $ref: '#/definitions/EmployeeReqPut'
  
  PartnerAllResp:
    type: object
    description: 合作伙伴全量信息响应实体
    properties:
      partner:
        $ref: '#/definitions/PartnerResp'
      partnerExt:
        $ref: '#/definitions/PartnerExtResp'
      partnerQualify:
        $ref: '#/definitions/PartnerQualifyResp'
      employee:
        $ref: '#/definitions/EmployeeResp'
        
  Partners:
    type: object
    description: 合作伙伴列表
    properties:
      page:
        $ref: '#/definitions/Page'
      data:
        type: array
        items:
          $ref: '#/definitions/PartnerResp'
  
  EmployeeReqPost:
    type: object
    description: 员工添加实体
    required:
    - empName
    - phone
    allOf:
    - $ref: '#/definitions/Employee'
  
  EmployeeReqPut:
    type: object
    description: 员工修改实体
    allOf:
    - $ref: '#/definitions/Employee'
  
  EmployeeResp:
    type: object
    description: 员工响应实体
    allOf:
    - $ref: '#/definitions/Employee'
    - $ref: '#/definitions/Gmt'
    properties:
      partnerId:
        type: integer
        description: 合作伙伴id
      empId:
        type: integer
        description: 员工id
        
  Employee:
    type: object
    description: 员工信息
    properties:
      empName:
        type: string
        description: 员工姓名
        minLength: 1
        maxLength: 10
      userId:
        type: integer
        description: 所属用户id
      jobName:
        type: string
        description: 员工岗位
        maxLength: 20
      sex:
        type: integer
        enum: 
          - 1
          - 2
          - 0
        description: 性别，0：未知，1：男，2：女
        default: 0
      email:
        type: string
        description: 邮箱，格式：xxx@yyy.zzz
        maxLength: 30
      phone:
        type: string
        description: 手机，只允许数字
        minLength: 11
        maxLength: 11
        pattern: '^\d{11}$'
      tel:
        type: string
        description: 固定电话，多个号码以英文逗号分隔，最多5个
        maxLength: 100
      im:
        type: string
        description: im联系方式
        maxLength: 20
      status:
        type: integer
        enum: 
          - 0
          - 1
        description: 状态，必填; 1：正常；0：停用
        default: 1

  Page:
    type: object
    description: 分页信息
    properties:
      page:
        type: integer
        description: 当前页码
      nextPage:
        type: integer
        description: 下一页页码
      prePage:
        type: integer
        description: 上一页页码
      totalPages:
        type: integer
        description: 总页数
      totalCount:
        type: integer
        description: 总记录数
      firstPage:
        type: boolean
        description: 是否为首页
      lastPage:
        type: boolean
        description: 是否为尾页
      hasPrePage:
        type: boolean
        description: 是否有上一页
      hasNextPage:
        type: boolean
        description: 是否有下一页
      startRow:
        type: integer
        description: 当前页起始行
      endRow:
        type: integer
        description: 当前页结束行
        
  Error:
    type: object
    description: 错误Bean
    required:
      - code
      - message
    properties:
      code:
        type: string
        description: 错误码
      message:
        type: string
        description: 错误描述
      errors:
        type: array
        description: 具体错误
        items:
          $ref: '#/definitions/ErrorMsg'
        
  ErrorMsg:
    type: object
    description: 错误消息详细信息
    properties:
      field:
        type: string
        description: 错误字段
      message:
        type: string
        description: 错误原因